spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/primes
    username: postgres
    password: Mercedes

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 4006
    username: guest
    password: guest

server:
  port:
    8085